name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.lock.txt'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install deps
        run: |
          npm install --legacy-peer-deps
      - name: build
        run: |
          npm run build |& tee -a $GITHUB_STEP_SUMMARY
          exit ${PIPESTATUS[0]}
      - name: SSG
        run: |
          npm run scully |& tee -a $GITHUB_STEP_SUMMARY
          exit ${PIPESTATUS[0]}
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/static/
